# Generated by Django 2.2.15 on 2021-01-21 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='doctor',
            new_name='doctor_name',
        ),
    ]
